/*
 * Allergen Database
 *
 * Maps ingredient names, derivatives, and synonyms to canonical allergen keys.
 * Used by the policy engine for deterministic allergen detection.
 *
 * Sources: FDA Top 9, EU Top 14, plus additional common allergens.
 * Each entry maps a lowercase ingredient term to its canonical allergen.
 */

export type CanonicalAllergen =
  | "Milk"
  | "Eggs"
  | "Peanuts"
  | "Tree nuts"
  | "Fish"
  | "Shellfish"
  | "Wheat"
  | "Soy"
  | "Sesame"
  | "Corn"
  | "Mustard"
  | "Lupin"
  | "Gelatin"
  | "Sulfites"
  | "Seeds";

/**
 * Map of lowercase ingredient terms → canonical allergen.
 * Includes derivatives, scientific names, and common label aliases.
 */
export const ALLERGEN_SYNONYM_MAP: Record<string, CanonicalAllergen> = {
  // ── MILK / DAIRY ──
  milk: "Milk",
  "whole milk": "Milk",
  "skim milk": "Milk",
  "nonfat milk": "Milk",
  "low-fat milk": "Milk",
  "reduced fat milk": "Milk",
  "milk powder": "Milk",
  "dry milk": "Milk",
  "dried milk": "Milk",
  "milk solids": "Milk",
  "milk protein": "Milk",
  "milk fat": "Milk",
  "condensed milk": "Milk",
  "evaporated milk": "Milk",
  buttermilk: "Milk",
  cream: "Milk",
  "heavy cream": "Milk",
  "light cream": "Milk",
  "sour cream": "Milk",
  "whipping cream": "Milk",
  "cream cheese": "Milk",
  butter: "Milk",
  "butter oil": "Milk",
  "butter fat": "Milk",
  butterfat: "Milk",
  ghee: "Milk",
  cheese: "Milk",
  cheddar: "Milk",
  parmesan: "Milk",
  mozzarella: "Milk",
  ricotta: "Milk",
  "cottage cheese": "Milk",
  yogurt: "Milk",
  yoghurt: "Milk",
  kefir: "Milk",
  whey: "Milk",
  "whey powder": "Milk",
  "whey protein": "Milk",
  "whey protein concentrate": "Milk",
  "whey protein isolate": "Milk",
  "sweet whey": "Milk",
  "acid whey": "Milk",
  casein: "Milk",
  caseinate: "Milk",
  "sodium caseinate": "Milk",
  "calcium caseinate": "Milk",
  "potassium caseinate": "Milk",
  curds: "Milk",
  lactalbumin: "Milk",
  "lactalbumin phosphate": "Milk",
  lactoglobulin: "Milk",
  lactose: "Milk",
  lactulose: "Milk",
  galactose: "Milk",
  "dairy": "Milk",
  "dairy product": "Milk",
  "milk derivative": "Milk",
  "half and half": "Milk",
  "half & half": "Milk",
  custard: "Milk",
  pudding: "Milk",
  nougat: "Milk",
  "ice cream": "Milk",
  gelato: "Milk",
  paneer: "Milk",
  "queso": "Milk",
  "fromage": "Milk",
  "crème fraîche": "Milk",
  "creme fraiche": "Milk",
  "dulce de leche": "Milk",
  "recaldent": "Milk",
  "simplesse": "Milk",
  "rennet casein": "Milk",

  // ── EGGS ──
  egg: "Eggs",
  eggs: "Eggs",
  "egg white": "Eggs",
  "egg whites": "Eggs",
  "egg yolk": "Eggs",
  "egg yolks": "Eggs",
  "whole egg": "Eggs",
  "dried egg": "Eggs",
  "egg powder": "Eggs",
  "powdered egg": "Eggs",
  "egg solids": "Eggs",
  "egg protein": "Eggs",
  albumin: "Eggs",
  albumen: "Eggs",
  "egg albumin": "Eggs",
  globulin: "Eggs",
  lysozyme: "Eggs",
  mayonnaise: "Eggs",
  mayo: "Eggs",
  meringue: "Eggs",
  ovalbumin: "Eggs",
  ovomucin: "Eggs",
  ovomucoid: "Eggs",
  ovovitellin: "Eggs",
  ovotransferrin: "Eggs",
  "egg lecithin": "Eggs",
  surimi: "Eggs",
  livetin: "Eggs",
  "fat substitute": "Eggs",
  eggnog: "Eggs",

  // ── PEANUTS ──
  peanut: "Peanuts",
  peanuts: "Peanuts",
  "peanut butter": "Peanuts",
  "peanut oil": "Peanuts",
  "peanut flour": "Peanuts",
  "peanut protein": "Peanuts",
  "ground nuts": "Peanuts",
  groundnuts: "Peanuts",
  "monkey nuts": "Peanuts",
  "earth nuts": "Peanuts",
  "beer nuts": "Peanuts",
  "arachis oil": "Peanuts",
  "arachis hypogaea": "Peanuts",
  "hydrolyzed peanut protein": "Peanuts",
  goober: "Peanuts",
  "goober peas": "Peanuts",
  "mandelonas": "Peanuts",
  "nu-nuts": "Peanuts",
  "nut meat": "Peanuts",
  satay: "Peanuts",

  // ── TREE NUTS ──
  almond: "Tree nuts",
  almonds: "Tree nuts",
  "almond butter": "Tree nuts",
  "almond milk": "Tree nuts",
  "almond flour": "Tree nuts",
  "almond extract": "Tree nuts",
  "almond paste": "Tree nuts",
  marzipan: "Tree nuts",
  cashew: "Tree nuts",
  cashews: "Tree nuts",
  "cashew butter": "Tree nuts",
  walnut: "Tree nuts",
  walnuts: "Tree nuts",
  pecan: "Tree nuts",
  pecans: "Tree nuts",
  pistachio: "Tree nuts",
  pistachios: "Tree nuts",
  "brazil nut": "Tree nuts",
  "brazil nuts": "Tree nuts",
  hazelnut: "Tree nuts",
  hazelnuts: "Tree nuts",
  filbert: "Tree nuts",
  filberts: "Tree nuts",
  macadamia: "Tree nuts",
  "macadamia nut": "Tree nuts",
  "macadamia nuts": "Tree nuts",
  "pine nut": "Tree nuts",
  "pine nuts": "Tree nuts",
  pignoli: "Tree nuts",
  praline: "Tree nuts",
  pralines: "Tree nuts",
  gianduja: "Tree nuts",
  "nutella": "Tree nuts",
  "nut butter": "Tree nuts",
  "nut oil": "Tree nuts",
  "nut paste": "Tree nuts",
  "nut extract": "Tree nuts",
  "nut meal": "Tree nuts",
  "nut flour": "Tree nuts",
  "mixed nuts": "Tree nuts",
  nougat: "Tree nuts",
  "shea nut": "Tree nuts",
  "lychee nut": "Tree nuts",
  "chestnut": "Tree nuts",
  chestnuts: "Tree nuts",
  "coconut": "Tree nuts",

  // ── FISH ──
  fish: "Fish",
  cod: "Fish",
  salmon: "Fish",
  tuna: "Fish",
  trout: "Fish",
  tilapia: "Fish",
  halibut: "Fish",
  haddock: "Fish",
  herring: "Fish",
  sardine: "Fish",
  sardines: "Fish",
  anchovy: "Fish",
  anchovies: "Fish",
  "anchovy paste": "Fish",
  "fish sauce": "Fish",
  "fish oil": "Fish",
  "fish gelatin": "Fish",
  "fish protein": "Fish",
  "fish stock": "Fish",
  "fish extract": "Fish",
  "fish meal": "Fish",
  "worcestershire sauce": "Fish",
  "caesar dressing": "Fish",
  "caesar salad dressing": "Fish",
  "imitation fish": "Fish",
  surimi: "Fish",
  swordfish: "Fish",
  mahi: "Fish",
  "mahi mahi": "Fish",
  bass: "Fish",
  "sea bass": "Fish",
  catfish: "Fish",
  perch: "Fish",
  pike: "Fish",
  pollock: "Fish",
  snapper: "Fish",
  sole: "Fish",
  mackerel: "Fish",
  grouper: "Fish",
  flounder: "Fish",
  "omega-3": "Fish",
  "dha": "Fish",
  "epa": "Fish",

  // ── SHELLFISH ──
  shellfish: "Shellfish",
  shrimp: "Shellfish",
  prawns: "Shellfish",
  crab: "Shellfish",
  lobster: "Shellfish",
  crayfish: "Shellfish",
  crawfish: "Shellfish",
  "crawdads": "Shellfish",
  clam: "Shellfish",
  clams: "Shellfish",
  mussel: "Shellfish",
  mussels: "Shellfish",
  oyster: "Shellfish",
  oysters: "Shellfish",
  "oyster sauce": "Shellfish",
  scallop: "Shellfish",
  scallops: "Shellfish",
  squid: "Shellfish",
  calamari: "Shellfish",
  octopus: "Shellfish",
  snail: "Shellfish",
  escargot: "Shellfish",
  "abalone": "Shellfish",
  "shellfish extract": "Shellfish",
  "crustacean": "Shellfish",
  "crustaceans": "Shellfish",
  "mollusk": "Shellfish",
  "mollusks": "Shellfish",
  "mollusc": "Shellfish",
  "chitin": "Shellfish",
  glucosamine: "Shellfish",
  "chitosan": "Shellfish",

  // ── WHEAT ──
  wheat: "Wheat",
  "wheat flour": "Wheat",
  "whole wheat": "Wheat",
  "whole wheat flour": "Wheat",
  "wheat starch": "Wheat",
  "wheat germ": "Wheat",
  "wheat bran": "Wheat",
  "wheat protein": "Wheat",
  "wheat gluten": "Wheat",
  "modified wheat starch": "Wheat",
  "hydrolyzed wheat protein": "Wheat",
  "hydrolyzed wheat gluten": "Wheat",
  gluten: "Wheat",
  "vital wheat gluten": "Wheat",
  semolina: "Wheat",
  durum: "Wheat",
  "durum wheat": "Wheat",
  "durum flour": "Wheat",
  spelt: "Wheat",
  kamut: "Wheat",
  farina: "Wheat",
  farro: "Wheat",
  einkorn: "Wheat",
  emmer: "Wheat",
  triticale: "Wheat",
  bulgur: "Wheat",
  couscous: "Wheat",
  seitan: "Wheat",
  "bread crumbs": "Wheat",
  breadcrumbs: "Wheat",
  "bread flour": "Wheat",
  "all-purpose flour": "Wheat",
  "all purpose flour": "Wheat",
  "enriched flour": "Wheat",
  "bleached flour": "Wheat",
  "unbleached flour": "Wheat",
  "self-rising flour": "Wheat",
  "cake flour": "Wheat",
  "pastry flour": "Wheat",
  "graham flour": "Wheat",
  "cracker meal": "Wheat",
  "matzoh": "Wheat",
  matzo: "Wheat",
  "matzo meal": "Wheat",
  "pasta": "Wheat",
  "noodles": "Wheat",
  orzo: "Wheat",
  panko: "Wheat",
  "roux": "Wheat",
  "fu": "Wheat",

  // ── SOY ──
  soy: "Soy",
  soya: "Soy",
  soybean: "Soy",
  soybeans: "Soy",
  "soy sauce": "Soy",
  "soy protein": "Soy",
  "soy protein isolate": "Soy",
  "soy protein concentrate": "Soy",
  "soy flour": "Soy",
  "soy milk": "Soy",
  "soy lecithin": "Soy",
  "soya lecithin": "Soy",
  "soybean oil": "Soy",
  "soy oil": "Soy",
  edamame: "Soy",
  miso: "Soy",
  tempeh: "Soy",
  tofu: "Soy",
  "bean curd": "Soy",
  tamari: "Soy",
  shoyu: "Soy",
  natto: "Soy",
  "textured vegetable protein": "Soy",
  tvp: "Soy",
  "textured soy protein": "Soy",
  "hydrolyzed soy protein": "Soy",
  "soy albumin": "Soy",
  "soy fiber": "Soy",
  "soy grits": "Soy",
  "soy nuts": "Soy",
  "soy sprouts": "Soy",
  "soy starch": "Soy",
  "vegetable protein": "Soy",
  "hydrolyzed vegetable protein": "Soy",
  "vegetable gum": "Soy",
  "vegetable starch": "Soy",
  lecithin: "Soy",
  "mono-diglyceride": "Soy",

  // ── SESAME ──
  sesame: "Sesame",
  "sesame seeds": "Sesame",
  "sesame oil": "Sesame",
  "sesame paste": "Sesame",
  "sesame flour": "Sesame",
  "sesame salt": "Sesame",
  tahini: "Sesame",
  tehina: "Sesame",
  hummus: "Sesame",
  halvah: "Sesame",
  halva: "Sesame",
  "benne seeds": "Sesame",
  "gingelly oil": "Sesame",
  "til oil": "Sesame",
  gomasio: "Sesame",
  "sesamum indicum": "Sesame",

  // ── CORN ──
  corn: "Corn",
  "corn flour": "Corn",
  "corn starch": "Corn",
  cornstarch: "Corn",
  "corn meal": "Corn",
  cornmeal: "Corn",
  "corn oil": "Corn",
  "corn syrup": "Corn",
  "high fructose corn syrup": "Corn",
  hfcs: "Corn",
  "corn protein": "Corn",
  "corn gluten": "Corn",
  maize: "Corn",
  "maize starch": "Corn",
  "modified corn starch": "Corn",
  "modified food starch": "Corn",
  dextrose: "Corn",
  dextrin: "Corn",
  maltodextrin: "Corn",
  "corn maltodextrin": "Corn",
  polenta: "Corn",
  hominy: "Corn",
  grits: "Corn",
  "masa": "Corn",
  "masa harina": "Corn",
  tortilla: "Corn",

  // ── MUSTARD ──
  mustard: "Mustard",
  "mustard seed": "Mustard",
  "mustard seeds": "Mustard",
  "mustard flour": "Mustard",
  "mustard oil": "Mustard",
  "mustard powder": "Mustard",
  "mustard greens": "Mustard",
  "dijon": "Mustard",
  "dijon mustard": "Mustard",

  // ── LUPIN ──
  lupin: "Lupin",
  lupine: "Lupin",
  "lupin flour": "Lupin",
  "lupin seed": "Lupin",
  "lupin beans": "Lupin",
  "lupini beans": "Lupin",

  // ── GELATIN ──
  gelatin: "Gelatin",
  gelatine: "Gelatin",
  "pork gelatin": "Gelatin",
  "beef gelatin": "Gelatin",
  "fish gelatin": "Gelatin",
  "hydrolyzed collagen": "Gelatin",
  "collagen peptides": "Gelatin",
  isinglass: "Gelatin",

  // ── SULFITES ──
  sulfite: "Sulfites",
  sulfites: "Sulfites",
  "sulfur dioxide": "Sulfites",
  "sulphur dioxide": "Sulfites",
  "sodium sulfite": "Sulfites",
  "sodium bisulfite": "Sulfites",
  "sodium metabisulfite": "Sulfites",
  "potassium bisulfite": "Sulfites",
  "potassium metabisulfite": "Sulfites",
  sulphite: "Sulfites",
  sulphites: "Sulfites",

  // ── SEEDS ──
  "sunflower seeds": "Seeds",
  "sunflower seed": "Seeds",
  "sunflower oil": "Seeds",
  "pumpkin seeds": "Seeds",
  "poppy seeds": "Seeds",
  "flax seeds": "Seeds",
  flaxseed: "Seeds",
  "flaxseed oil": "Seeds",
  "linseed": "Seeds",
  "chia seeds": "Seeds",
  "hemp seeds": "Seeds",
  "hemp seed": "Seeds",
};

/**
 * Reverse lookup: canonical allergen → all synonym terms.
 */
export function getSynonymsForAllergen(allergen: CanonicalAllergen): string[] {
  return Object.entries(ALLERGEN_SYNONYM_MAP)
    .filter(([_, canonical]) => canonical === allergen)
    .map(([term]) => term);
}

/**
 * All canonical allergen names (matching the UI options).
 */
export const ALL_CANONICAL_ALLERGENS: CanonicalAllergen[] = [
  "Milk",
  "Eggs",
  "Peanuts",
  "Tree nuts",
  "Fish",
  "Shellfish",
  "Wheat",
  "Soy",
  "Sesame",
  "Corn",
  "Mustard",
  "Lupin",
  "Gelatin",
  "Sulfites",
  "Seeds",
];
